[workspace]
members = ["oxanus", "oxanus-macros"]
resolver = "3"
default-members = ["oxanus"]

[workspace.package]
rust-version = "1.75"

[workspace.dependencies]
oxanus = { path = "oxanus" }
oxanus-macros = { path = "oxanus-macros" }
